import React from 'react';
import { SketchyCard } from './ui/sketchy-card';
import { AdAnalysis } from '@/lib/ad-utils';
import { AlertTriangle, Target, Gavel } from 'lucide-react';
interface AnalysisResultProps {
  data: AdAnalysis;
}
export function AnalysisResult({ data }: AnalysisResultProps) {
  return (
    <div className="w-full max-w-xl mx-auto space-y-8 py-8">
      <SketchyCard title="Detected" variant="yellow" delay={0.1}>
        <div className="flex gap-4 items-start">
          <AlertTriangle className="shrink-0 mt-1" />
          <p className="text-lg">{data.detected}</p>
        </div>
      </SketchyCard>
      <SketchyCard title="The Trap" variant="pink" delay={0.3}>
        <div className="flex gap-4 items-start">
          <Target className="shrink-0 mt-1" />
          <p className="text-lg">{data.trap}</p>
        </div>
      </SketchyCard>
      <SketchyCard title="Verdict" variant="cyan" delay={0.5}>
        <div className="flex gap-4 items-start">
          <Gavel className="shrink-0 mt-1" />
          <div className="space-y-2">
            <p className="text-xl font-black uppercase tracking-tighter">
              {data.verdict}
            </p>
            {data.price_comparison && (
              <p className="text-sm border-t border-black/20 pt-2 italic">
                Market Intel: {data.price_comparison}
              </p>
            )}
          </div>
        </div>
      </SketchyCard>
      <div className="text-center pt-4">
        <p className="text-xs text-muted-foreground uppercase font-bold tracking-widest">
          Analysis generated by AdXRay AI Model
        </p>
      </div>
    </div>
  );
}